# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Install following packages as root
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - name: include JupyterHub configuration variables
      include_vars:
        file: vars/jupyter_vars.yml
        name: jupyter_vars

    - name: Delete jupyterhub and its dependencies
      include_role:
        name: jupyterhub_deleted
