# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Install following packages as root
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - name: include JupyterHub configuration variables
      include_vars:
        file: vars/jupyter_vars.yml
        name: jupyter_vars

    - name: Install python environment
      include_role:
        name: python_pip_installed

    - name: Install virtualenvwrapper
      include_role:
        name: virtualenvwrapper_initialized

    - name: Install configurable-http-proxy globally
      include_role:
        name: configurable_http_proxy

    - name: Install jupyterhub globally
      include_role:
        name: jupyterhub

    - name: Make sure SSL certificates exist
      include_role:
        name: ssl_certificates

    - name: Ensure that jupyterhub users are present
      include_role:
        name: jupyterhub_users

    - name: Ensure that jupyterhub is properly configured
      include_role:
        name: jupyterhub_configured

    - name: Install Supervisor
      include_role:
        name: supervisor

    - name: Ensure that JupyterHub configuration for Supervisor is set
      include_role:
        name: supervisor_configured

    - name: Ensure that JupyterHub started
      include_role:
        name: jupyterhub_started

    - name: Remove deleted users
      include_role:
        name: remove_jupyterhub_users
