# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Make virutal environment global
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - name: Install ipykernel
      pip:
        name: ipykernel
        state: present
        virtualenv: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}"
        virtualenv_python: python3

    # NB! Name is important for backend logic!
    - name: Final list of all installed libraries in the venv
      shell: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}/bin/pip freeze"
      args:
        executable: /bin/bash

    - name: Make virutal environment global
      script: "files/make_virtual_env_global.sh /home/{{default_system_user}}/{{virtual_envs_dir_path}} {{virtual_env_name}}"
