# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Make virutal environment local
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - name: Make virutal environment local
      script: "files/make_virtual_env_local.sh /home/{{default_system_user}}/{{virtual_envs_dir_path}} {{virtual_env_name}}"

    # NB! Name is important for backend logic!
    - name: Final list of all installed libraries in the venv
      shell: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}/bin/pip freeze"
      args:
        executable: /bin/bash
