# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Set workon home path
  action:
    module: lineinfile
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "export WORKON_HOME"
    line: "export WORKON_HOME={{ ansible_env.HOME }}/{{virtual_envs_dir_path}}/"
    state: present
    backup: yes

# be aware that these variables is impossible to load in ansible
- name: Add virtualenvwrapper.sh to bashrc
  action:
    module: lineinfile
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "source /usr/local/bin/virtualenvwrapper.sh"
    line: "source /usr/local/bin/virtualenvwrapper.sh"
    state: present
    backup: yes

- name: trigger virtualenvs directory creation
  shell: "export WORKON_HOME=/home/{{default_system_user}}/{{virtual_envs_dir_path}} && . /usr/local/bin/virtualenvwrapper.sh"
  args:
    executable: /bin/bash