# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: install jupyterhub launch script
  template:
    src: run_jupyterhub.sh.j2
    dest: "{{jupyter_vars.jupyterhub_dir}}/start-jupyterhub.sh"
    mode: '0700'
    backup: yes

- name: install supervisor config for jupyterhub
  template:
    src: supervisor_jupyterhub.config.j2
    dest: /etc/supervisor/conf.d/jupyterhub.conf
    owner: root
    group: root
    mode: '0600'

- name: load jupyterhub supervisor config
  supervisorctl:
    name: jupyterhub
    state: present