# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Remove virtual environment
  hosts: vm_instance_to_configure
  become: yes
  tasks:
    - name: Make virutal environment local if possible
      script: "files/make_virtual_env_local.sh /home/{{default_system_user}}/{{virtual_envs_dir_path}} {{virtual_env_name}}"
      ignore_errors: yes

    - name: Remove virtual environment
      file:
        state: absent
        path: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}"
