# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Remove virtual environments directory
  hosts: vm_instance_to_configure
  become: yes
  tasks:
    - name: Remove virtual environments directory
      file:
        state: absent
        path: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/"
