# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Get an OpenStack instance
  connection: local
  hosts: localhost
  roles:
    - connection

- name: Remove virtual environment
  hosts: vm_instance_to_configure
  become: yes
  become_user: "{{default_system_user}}"
  tasks:
    - name: Remove virtual environment
      file:
        state: absent
        path: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}"