# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Get an OpenStack instance
  connection: local
  hosts: localhost
  roles:
    - connection

- name: Find installed packages in the venv
  hosts: vm_instance_to_configure
  tasks:
    - name: Final list of all installed libraries in the venv
      shell: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}/{{virtual_env_name}}/bin/pip freeze"
      args:
        executable: /bin/bash