# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: List all environments
  hosts: vm_instance_to_configure
  tasks:
    - name: list all installed virtual environments
      shell: ". /usr/local/bin/virtualenvwrapper.sh && lsvirtualenv -b"
      args:
        executable: /bin/bash
      environment:
        WORKON_HOME: "/home/{{default_system_user}}/{{virtual_envs_dir_path}}"
