# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Get an OpenStack instance
  connection: local
  hosts: localhost
  roles:
    - connection

- name: Install python environment
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - include_role:
        name: python_pip_installed

- name: Initialize virtualenvwrapper
  hosts: vm_instance_to_configure
  become: yes
  become_user: "{{default_system_user}}"
  tasks:
    - include_role:
        name: virtualenvwrapper_initialized