# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Initialize inventory
  connection: local
  hosts: localhost
  roles:
    - inventory_initialized

- name: Install python environment & identify exact python version
  become: yes
  hosts: vm_instance_to_configure
  gather_facts: false
  # Ansible requires python2, which is not installed by default on some distributions
  pre_tasks:
   - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
   # action: setup will gather facts after python2 has been installed
   - action: setup
  tasks:
    - name: Install python environment
      include_role:
        name: python_pip_installed
    #NB! name is important for backend logic!
    - name: Identify installed python version
      command: python3 -V

- name: Initialize virtualenvwrapper
  hosts: vm_instance_to_configure
  become: yes
  become_user: "{{default_system_user}}"
  tasks:
    - include_role:
        name: virtualenvwrapper_initialized
