# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-
---
- name: Get an OpenStack instance
  connection: local
  hosts: localhost
  roles:
    - connection

- name: Install python environment & identify exact python version
  become: yes
  hosts: vm_instance_to_configure
  tasks:
    - name: Install python environment
      include_role:
        name: python_pip_installed
    #NB! name is important for backend logic!
    - name: Identify installed python version
      command: python3 -V

- name: Initialize virtualenvwrapper
  hosts: vm_instance_to_configure
  become: yes
  become_user: "{{default_system_user}}"
  tasks:
    - include_role:
        name: virtualenvwrapper_initialized