# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: add instance to dynamic inventory of current playbook execution
  add_host:
    ansible_ssh_private_key_file: "{{ private_key_path }}"
    ansible_user: "{{default_system_user}}"
    groups: vm_instance_to_configure
    hostname: "{{ instance_public_ip }}"
